const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  analyzePassage: (payload) => ipcRenderer.invoke('analyze-passage', payload),
  historyList: () => ipcRenderer.invoke('history-list'),
  historyDelete: (id) => ipcRenderer.invoke('history-delete', id),
  historySaveAnnotations: (id, annotations) => ipcRenderer.invoke('history-save-annotations', { id, annotations }),
  getCrossRefs: (payload) => ipcRenderer.invoke('get-cross-refs', payload),
  wordStudy: (payload) => ipcRenderer.invoke('word-study', payload),
  exportPdf: (payload) => ipcRenderer.invoke('export-pdf', payload),
  scholarChat: (payload) => ipcRenderer.invoke('scholar-chat', payload),
  fetchEsv: (payload) => ipcRenderer.invoke('fetch-esv', payload),
  profileGet: () => ipcRenderer.invoke('profile-get'),
  profileSave: (profile) => ipcRenderer.invoke('profile-save', profile),
  profileAddSermon: (payload) => ipcRenderer.invoke('profile-add-sermon', payload),
  profileExtractInsights: (payload) => ipcRenderer.invoke('profile-extract-insights', payload),
  profileSearchSermons: (query) => ipcRenderer.invoke('profile-search-sermons', query),
  profileGetSermon: (id) => ipcRenderer.invoke('profile-get-sermon', id),
  draftSermon: (payload) => ipcRenderer.invoke('draft-sermon', payload),
  agentChat: (payload) => ipcRenderer.invoke('agent-chat', payload),
  flagManuscript: (payload) => ipcRenderer.invoke('eisegesis-check', payload),
  sessionUpdateDraft: (id, draft) => ipcRenderer.invoke('session-update-draft', { id, draft }),
  sessionUpdateChat: (id, scholarMessages) => ipcRenderer.invoke('session-update-chat', { id, scholarMessages }),
  sessionLoadLatest: () => ipcRenderer.invoke('session-load-latest'),
  fetchCommentary: (payload) => ipcRenderer.invoke('fetch-commentary', payload),
  seriesList: () => ipcRenderer.invoke('series-list'),
  seriesCreate: (payload) => ipcRenderer.invoke('series-create', payload),
  seriesAddPassage: (payload) => ipcRenderer.invoke('series-add-passage', payload),
  seriesRemovePassage: (payload) => ipcRenderer.invoke('series-remove-passage', payload),
  seriesDelete: (id) => ipcRenderer.invoke('series-delete', id),
  seriesSynthesize: (payload) => ipcRenderer.invoke('series-synthesize', payload),
  scanAssetImages: () => ipcRenderer.invoke('scan-asset-images'),
})
